### ISSUE TITLE
es_manage --rebuild fails

### ISSUE THREAD

**Issue by zerotao** [jaddison/django-simple-elasticsearch#14]
``` python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/vagrant/venv/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/vagrant/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/vagrant/venv/local/lib/python2.7/site-packages/simple_elasticsearch/management/commands/es_manage.py", line 76, in handle
    self.subcommand_rebuild(requested_indexes, no_input)
  File "/vagrant/venv/local/lib/python2.7/site-packages/simple_elasticsearch/management/commands/es_manage.py", line 112, in subcommand_rebuild
    results, aliases = rebuild_indices(indices=indexes)
  File "/vagrant/venv/local/lib/python2.7/site-packages/simple_elasticsearch/utils.py", line 174, in rebuild_indices
    }}, index=index_name)
  File "/vagrant/venv/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/vagrant/venv/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 618, in put_settings
    '_settings'), params=params, body=body)
  File "/vagrant/venv/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/vagrant/venv/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/vagrant/venv/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception')
```

I put an exception handler around es.indeces.put_settings and grabbed the info section of the ES error:

```
Can't update non dynamic settings[[index.merge.policy.merge_factor]] for open indices [[...]]
```

**Comment by jaddison** [comment]
I suspect that you're using a version of elasticsearch not supported by the `master` branch of this project. I've used `master` with 1.7.x, but I use the `es2.0` branch with Elasticsearch 2.3.x successfully.

**Comment by zerotao** [comment]
That could very well be the issue.

**Comment by jaddison** [comment]
Closing.
