### ISSUE TITLE
missing signals.py?

### ISSUE THREAD

**Issue by key** [jaddison/django-simple-elasticsearch#6]
Hi,

`simple_elasticsearch.utils` module needs signals, but it does not commited.

# Environment
OS: MacOSX 10.10
Python: 3.4.2

# Repro steps
* install library from HEAD `pip install -e git+https://github.com/jaddison/django-simple-elasticsearch.git#egg=django-simple-elasticsearch`
* type `python manage.py es_manage --list`

# Expected result
* No import error.

# Stacktrace
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/key/Documents/virtualenv/photoshare/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/key/Documents/virtualenv/photoshare/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/key/Documents/virtualenv/photoshare/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/key/Documents/virtualenv/photoshare/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/key/Documents/virtualenv/photoshare/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/key/Documents/virtualenv/photoshare/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/key/Documents/virtualenv/photoshare/photoshare/apps/album/models.py", line 11, in <module>
    from apps.event.models import Event
  File "/Users/key/Documents/virtualenv/photoshare/photoshare/apps/event/models.py", line 7, in <module>
    from simple_elasticsearch.mixins import ElasticsearchIndexMixin
  File "/Users/key/Documents/virtualenv/photoshare/src/django-simple-elasticsearch/simple_elasticsearch/mixins.py", line 5, in <module>
    from .utils import queryset_iterator
  File "/Users/key/Documents/virtualenv/photoshare/src/django-simple-elasticsearch/simple_elasticsearch/utils.py", line 11, in <module>
    from .signals import post_indices_create, post_indices_rebuild
ImportError: No module named 'simple_elasticsearch.signals'
```

# Note

`simple_elasticsearch/utils.py`

```
from .signals import post_indices_create, post_indices_rebuild  # <- misssing file!
```

**Comment by jaddison** [comment]
This has been addressed in bc43ca5b4e. I can't believe I forgot to add it in. Sorry for the inconvenience!

PyPi has also been updated with a new package.
